name: npm run build

on:
  push:
    branches: ["main"]
    paths:
      - ./frontend
      - ./supabase
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend
